# Generated by Django 3.0.8 on 2020-07-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200713_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
